#!/usr/bin/env bun
/**
 * Regenerates protocol/example-requests.md by running a real probe against a fixture server and
 * recording what actually arrived.
 *
 * Written this way rather than by hand so it cannot drift from the code: if the prober starts
 * sending something else, this file changes, and the change is visible in review.
 */
import { probeTarget } from '../../src/stages/probe.js';
import { FixtureServer } from '../fixtures/server.js';
import { makeGate } from '../helpers/harness.js';
import { CONTACT_URL, USER_AGENT } from '../../src/config/identity.js';

const server = new FixtureServer({ kind: 'open' });
server.start();

const { gate, hostState } = makeGate();
await probeTarget(gate, hostState, {
  targetId: 'example',
  orgKey: 'example',
  origin: server.url,
  path: server.mcpPath,
});

const captures = gate.capturesFor('example');
await server.stop();

const lines: string[] = [
  '# Exactly what this scanner sends',
  '',
  'Generated by `tests/support/capture-example-requests.ts` from a real probe against a local',
  'fixture server, so it cannot drift from the code. If the prober starts sending something else,',
  'this file changes.',
  '',
  'An operator deciding whether to care about us should not have to read our source, or take our',
  'word for it. This is the whole of it.',
  '',
  `Identity on every request: \`${USER_AGENT}\``,
  `Opt out: ${CONTACT_URL}/blob/main/OPTOUT.md`,
  '',
  '## The complete sequence for one host',
  '',
  `${captures.length} HTTP requests against an open server. There is no branch that makes more, and`,
  'most hosts see fewer: a server that declines via the well-known gets one request and nothing',
  'else, and a server that answers with a credential challenge gets no second attempt.',
  '',
];

for (const [index, capture] of captures.entries()) {
  const url = new URL(capture.url);
  lines.push(`### ${index + 1}. \`${capture.method} ${url.pathname}\``);
  lines.push('');
  lines.push('```http');
  lines.push(`${capture.method} ${url.pathname} HTTP/1.1`);
  for (const [name, value] of capture.requestHeaders) {
    lines.push(`${name}: ${value}`);
  }
  lines.push('```');
  lines.push('');
  lines.push(`Response: \`${capture.status ?? 'error'}\`, ${capture.bodyBytes} bytes.`);

  const accept = new Map(capture.requestHeaders).get('accept') ?? '';
  if (capture.method === 'GET' && accept.includes('text/event-stream')) {
    lines.push('');
    lines.push(
      'This one the scanner does not originate: it is the MCP SDK opening the server-to-client ' +
        'stream that the Streamable HTTP transport uses. We disclose it rather than omit it, ' +
        'because it is a request you will see in your logs. It carries no JSON-RPC method, it is ' +
        'counted against the same per-host request budget as everything else, and it goes through ' +
        'the same gate — a request the SDK makes to any origin the ticket does not name is refused ' +
        'before it opens a socket.',
    );
  }
  lines.push('');
}

lines.push('## The JSON-RPC bodies');
lines.push('');
lines.push('Two methods, and the notification the protocol requires between them:');
lines.push('');
lines.push('```json');
lines.push(JSON.stringify({ jsonrpc: '2.0', id: 0, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'mcp-observatory', version: '0.1.0-alpha.1' } } }, null, 2));
lines.push('```');
lines.push('');
lines.push('```json');
lines.push(JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }, null, 2));
lines.push('```');
lines.push('');
lines.push('```json');
lines.push(JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list', params: {} }, null, 2));
lines.push('```');
lines.push('');
lines.push('There is no `tools/call`. The transport this scanner uses cannot represent one — see');
lines.push('`src/mcp/gated-transport.ts` and `tests/constraints/constraint-01-no-tool-invocation.test.ts`.');
lines.push('');
lines.push('Before any of the above, the scanner requests `/.well-known/mcp-scan-optout`. If that says');
lines.push('to go away, none of the above happens. See `protocol/MCP-SCAN-OPTOUT.md`.');
lines.push('');

await Bun.write('protocol/example-requests.md', lines.join('\n'));
process.stdout.write(`wrote protocol/example-requests.md (${captures.length} captured requests)\n`);
