/**
 * Stage 1. Build a candidate list. Contacts no MCP server.
 *
 * The only outbound traffic here is to the discovery sources themselves — certificate-transparency
 * logs and public registries — and it still goes through the gate, because "the gate is the only
 * code that reaches the network" is not a rule worth having if it has an exception for the
 * convenient case.
 *
 * The design decision that matters most is the last one: deduplicating by ORGANIZATION rather than
 * by hostname. One company with four regional endpoints is one data point, or every server-level
 * statistic is silently weighted by how many subdomains a company happens to run.
 */
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { canonicalHash } from '../canon/json.js';
import { registrableDomain } from '../net/optout.js';
import { TargetTicket } from '../net/ticket.js';
import type { Gate } from '../net/gate.js';

export type SourceId = 'ct' | 'registry' | 'path-candidate' | 'seed';

export type Confidence = 'primary' | 'lower';

export interface Candidate {
  readonly host: string;
  readonly path: string;
  readonly source: SourceId;
  readonly confidence: Confidence;
  /** Free-text note about where exactly this came from. Kept for auditability. */
  readonly provenance: string;
}

export interface Organization {
  readonly orgKey: string;
  /** Opaque and stable: a hash of the registrable domain. The derived tier never holds a hostname. */
  readonly registrableDomain: string;
  readonly candidates: readonly Candidate[];
  /** Every hostname collapsed into this organization, so the collapse can be audited. */
  readonly collapsedFrom: readonly string[];
}

export interface DiscoverManifest {
  readonly manifestHash: string;
  readonly organizations: readonly Organization[];
  /** Distinct (host, path) pairs. The real population size. */
  readonly candidateCount: number;
  /** Rows before deduplication. Kept only so the ratio is visible rather than flattering. */
  readonly rawRowCount: number;
  readonly sources: readonly (readonly [SourceId, number])[];
}

/**
 * Reserved and private-use suffixes (RFC 2606, RFC 6761, RFC 8375) plus the conventional local ones.
 * Certificate logs carry plenty of these. They are never publicly reachable, so including them would
 * pad the discovered population with hosts guaranteed to record as `unreachable` — inflating the
 * denominator of every server-level statistic with entries that were never candidates at all.
 */
const NON_ROUTABLE_SUFFIXES: readonly string[] = [
  '.local', '.localhost', '.internal', '.intranet', '.private', '.corp', '.home',
  '.home.arpa', '.lan', '.test', '.example', '.invalid', '.arpa', '.onion',
];

export function isRoutableHost(host: string): boolean {
  const lower = host.toLowerCase();
  return !NON_ROUTABLE_SUFFIXES.some((suffix) => lower === suffix.slice(1) || lower.endsWith(suffix));
}

export interface SharedPlatformRules {
  readonly version: string;
  readonly platforms: readonly string[];
}

export async function loadSharedPlatforms(dir = 'rules'): Promise<SharedPlatformRules> {
  return JSON.parse(await readFile(join(dir, 'shared-platforms.json'), 'utf8')) as SharedPlatformRules;
}

/** Certificate transparency. The primary source, and free. */
export async function discoverFromCertificateTransparency(
  gate: Gate,
  patterns: readonly string[] = ['mcp.%', '%-mcp.%', 'mcp-%'],
): Promise<readonly Candidate[]> {
  const candidates: Candidate[] = [];

  for (const pattern of patterns) {
    const url = `https://crt.sh/?q=${encodeURIComponent(pattern)}&output=json`;
    const ticket = new TargetTicket(
      `discover:crt.sh:${pattern}`,
      'https://crt.sh',
      '/',
      'http-metadata',
      new Set(['GET']),
      2,
    );

    let rows: readonly { name_value?: string }[];
    try {
      const response = await gate.fetch(ticket, url, { method: 'GET' });
      if (!response.ok) continue;
      rows = (await response.json()) as readonly { name_value?: string }[];
    } catch {
      // A discovery source being down is a smaller problem than a discovery source being trusted
      // blindly. Skip it; the manifest records which sources contributed.
      continue;
    }

    for (const row of rows) {
      for (const raw of (row.name_value ?? '').split('\n')) {
        const host = raw.trim().toLowerCase();
        if (host === '' || host.startsWith('*.')) continue;
        if (!/^[a-z0-9.-]+$/.test(host)) continue;
        candidates.push({
          host,
          path: '/mcp',
          source: 'ct',
          confidence: 'primary',
          provenance: `crt.sh q=${pattern}`,
        });
      }
    }
  }

  return candidates;
}

/**
 * For domains already known to serve APIs. Lower confidence and marked as such, because a candidate
 * generated by guessing a path is a guess, and the report says which figures rest on guesses.
 */
export function pathCandidates(domains: readonly string[]): readonly Candidate[] {
  const paths = ['/mcp', '/api/mcp', '/sse'];
  return domains.flatMap((domain) =>
    paths.map((path) => ({
      host: domain,
      path,
      source: 'path-candidate' as const,
      confidence: 'lower' as const,
      provenance: `generated path candidate for ${domain}`,
    })),
  );
}

/**
 * Collapse hostnames to organizations.
 *
 * `eu.mcp.acme.com` and `us.mcp.acme.com` are Acme, once. The org key is a hash rather than the
 * domain so that the derived tier — which is published — never carries a hostname at all.
 */
export async function collapseToOrganizations(
  candidates: readonly Candidate[],
  sharedPlatforms: readonly string[] = [],
): Promise<readonly Organization[]> {
  const shared = new Set(sharedPlatforms.map((p) => p.toLowerCase()));
  const byDomain = new Map<string, Candidate[]>();

  for (const candidate of candidates) {
    if (!isRoutableHost(candidate.host)) continue;

    const domain = registrableDomain(candidate.host);

    // No registrable domain means no public suffix: a bare internal name like `mcp`, which
    // certificate logs are full of. It is not reachable and not an organization.
    if (domain === null) continue;

    // On a shared platform the collapse runs the wrong way. Thirty-one unrelated projects on
    // *.hosted.app are one registrable domain and would count as one data point, silently
    // discarding thirty of them, so each host stays its own organization.
    const key = shared.has(domain) ? candidate.host : domain;

    const list = byDomain.get(key) ?? [];
    list.push(candidate);
    byDomain.set(key, list);
  }

  const organizations = await Promise.all(
    [...byDomain.entries()]
      .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
      .map(async ([domain, list]) => {
        const sorted = [...list].sort((a, b) =>
          a.host !== b.host
            ? a.host < b.host
              ? -1
              : 1
            : a.path < b.path
              ? -1
              : a.path > b.path
                ? 1
                : 0,
        );
        const hosts = [...new Set(sorted.map((c) => c.host))].sort();
        return {
          orgKey: (await canonicalHash({ registrableDomain: domain })).slice(0, 16),
          registrableDomain: domain,
          candidates: sorted,
          collapsedFrom: hosts,
        };
      }),
  );

  return organizations;
}

/**
 * Certificate logs return one row per certificate, so the same hostname arrives many times over —
 * in the first live run, 2,839 rows were 142 distinct hosts. Counting rows would overstate the
 * population by a factor of twenty.
 */
export function deduplicate(candidates: readonly Candidate[]): readonly Candidate[] {
  const seen = new Map<string, Candidate>();
  for (const candidate of candidates) {
    const key = `${candidate.host}|${candidate.path}`;
    const existing = seen.get(key);
    // Keep the highest-confidence provenance for a host we saw from several sources.
    if (existing === undefined || (existing.confidence === 'lower' && candidate.confidence === 'primary')) {
      seen.set(key, candidate);
    }
  }
  return [...seen.values()];
}

export async function buildDiscoverManifest(
  candidates: readonly Candidate[],
  sharedPlatforms: readonly string[] = [],
): Promise<DiscoverManifest> {
  const deduped = deduplicate(candidates);
  const organizations = await collapseToOrganizations(deduped, sharedPlatforms);

  const sourceCounts = new Map<SourceId, number>();
  for (const candidate of deduped) {
    sourceCounts.set(candidate.source, (sourceCounts.get(candidate.source) ?? 0) + 1);
  }

  const manifestHash = await canonicalHash(
    organizations.map((org) => [
      org.orgKey,
      org.candidates.map((c) => [c.host, c.path, c.source] as const),
    ]),
  );

  return {
    manifestHash,
    organizations,
    candidateCount: deduped.length,
    rawRowCount: candidates.length,
    sources: [...sourceCounts.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1)),
  };
}
