#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Publishing an OpenPGP key for observatory@forgestack.dev, the contact
# address in DISCLOSURE.md, OPTOUT.md and SECURITY.md.
#
# Everything here is a step the agent cannot take for you. Generating the key
# means choosing a passphrase, and a passphrase that passes through an AI
# session is not a passphrase. The key material never leaves this machine.
#
# Re-runnable: the key expires in two years, and rotation follows the same
# path.
# ──────────────────────────────────────────────────────────────────────────

KEY_UID_NAME="MCP Observatory"
KEY_UID_EMAIL="observatory@forgestack.dev"
KEY_FILE="security/observatory-pubkey.asc"
FPR_FILE="security/observatory-pubkey.fingerprint"
REVOKE_DIR="$HOME/.gnupg/openpgp-revocs.d"

TOTAL_STAGES=7

banner "Publish an OpenPGP key for $KEY_UID_EMAIL"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Install GnuPG"
if command -v gpg >/dev/null 2>&1; then
  say "GnuPG is already installed: $(gpg --version | head -1)"
else
  say "GnuPG is not installed. It is the tool that generates and holds the key."
  if command -v brew >/dev/null 2>&1; then
    step "Run this in another terminal, or let this wizard do it:"
    say "    brew install gnupg"
    if confirm "Install GnuPG now with Homebrew?"; then
      brew install gnupg
    else
      say "Install it yourself, then re-run this wizard."
      exit 1
    fi
  else
    step "Install GnuPG for your platform, then re-run:"
    say "    macOS    brew install gnupg"
    say "    Debian   sudo apt install gnupg"
    say "    Windows  https://gpg4win.org"
    exit 1
  fi
fi
command -v gpg >/dev/null 2>&1 || { printf '  %sgpg still not on PATH%s\n' "$RED" "$RESET"; exit 1; }
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Generate the keypair"
if gpg --list-secret-keys "$KEY_UID_EMAIL" >/dev/null 2>&1; then
  say "A secret key for $KEY_UID_EMAIL already exists. Skipping generation."
else
  say "GnuPG will ask you six questions. Answer them exactly as below."
  say ""
  step "Kind of key:      1   (RSA and RSA)"
  step "Keysize:          4096"
  step "Valid for:        2y"
  step "Real name:        $KEY_UID_NAME"
  step "Email address:    $KEY_UID_EMAIL"
  step "Comment:          (leave blank, then confirm with O)"
  say ""
  say "RSA rather than an elliptic curve, deliberately: this key exists so that"
  say "strangers can encrypt to it, and RSA-4096 is the option their mail client"
  say "is most likely to understand. Interoperability beats elegance here."
  say ""
  say "Then choose a passphrase. Use your password manager to generate and store"
  say "it. If you lose it you cannot read anything reported to you, and you"
  say "cannot revoke the key except with the certificate from stage 5."
  pause "Press Enter to start gpg --full-generate-key"
  gpg --full-generate-key
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Record the fingerprint"
FPR=$(gpg --list-keys --with-colons "$KEY_UID_EMAIL" 2>/dev/null | awk -F: '/^fpr:/ { print $10; exit }')
if [[ -z "$FPR" ]]; then
  printf '  %sCould not read a fingerprint for %s%s\n' "$RED" "$KEY_UID_EMAIL" "$RESET"
  exit 1
fi
say "Fingerprint:"
printf '  %s%s%s\n' "$BOLD" "$FPR" "$RESET"
mkdir -p "$(dirname "$FPR_FILE")"
printf '%s\n' "$FPR" > "$FPR_FILE"
say ""
say "Written to $FPR_FILE, so it can be wired into src/config/identity.ts,"
say "DISCLOSURE.md and SECURITY.md without you retyping 40 hex characters."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Export the public key"
gpg --armor --export "$FPR" > "$KEY_FILE"
if ! grep -q "BEGIN PGP PUBLIC KEY BLOCK" "$KEY_FILE"; then
  printf '  %sExport produced no armoured key%s\n' "$RED" "$RESET"
  exit 1
fi
say "Public key written to $KEY_FILE ($(wc -c < "$KEY_FILE" | tr -d ' ') bytes)."
say ""
say "This file is public and belongs in the repository. It is the half of the"
say "keypair that lets someone encrypt TO you; it cannot decrypt anything."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Secure the revocation certificate"
say "GnuPG generated a revocation certificate when it made the key. It is the"
say "only way to tell the world the key is dead if you lose the passphrase or"
say "the key is compromised."
say ""
if [[ -d "$REVOKE_DIR" ]]; then
  step "It is here:"
  say "    $REVOKE_DIR/${FPR}.rev"
else
  step "Look for it under ~/.gnupg/openpgp-revocs.d/"
fi
say ""
step "Copy it somewhere offline and private: a password manager attachment, or"
say "  encrypted storage. NOT this repository — publishing it lets anyone"
say "  revoke your key."
say ""
step "Back up the secret key the same way:"
say "    gpg --armor --export-secret-keys $FPR > observatory-secret.asc"
say "  Store that file offline and delete the local copy when done."
pause "Press Enter once the revocation certificate is safely stored"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Publish to a keyserver (optional)"
say "keys.openpgp.org is the usual place. It verifies the address before it"
say "will serve the key with an email attached, so you will receive a"
say "confirmation message at $KEY_UID_EMAIL and have to click a link."
say ""
say "Worth doing: it means a reporter who only has your address can find the"
say "key without visiting the repository. Skipping is fine, since the key is"
say "published in the repo either way."
if confirm "Upload to keys.openpgp.org now?"; then
  gpg --keyserver hkps://keys.openpgp.org --send-keys "$FPR" \
    && say "Uploaded. Check $KEY_UID_EMAIL for the verification link." \
    || say "Upload failed. Not fatal: the key is still published in the repo."
  open_url "https://keys.openpgp.org/upload"
else
  say "Skipped."
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Prove the key can actually receive mail"
say "The point of publishing a key is that a stranger can encrypt a finding to"
say "it and you can read it. Anything less than a round trip is an assumption,"
say "and this repository has already shipped two contact channels that did not"
say "work. So: encrypt a test message to the published key and decrypt it."
say ""
TEST_PLAIN="observatory key round-trip $(date -u +%Y-%m-%dT%H:%M:%SZ)"
if printf '%s' "$TEST_PLAIN" | gpg --armor --encrypt --recipient "$FPR" --trust-model always 2>/dev/null \
     | gpg --decrypt 2>/dev/null | grep -qF "$TEST_PLAIN"; then
  printf '  %s✓ Round trip succeeded: the key encrypts and decrypts.%s\n' "$GREEN" "$RESET"
else
  printf '  %s✗ Round trip FAILED. Do not advertise this key yet.%s\n' "$RED" "$RESET"
  say "  Investigate before wiring the fingerprint into the documents."
  exit 1
fi
say ""
say "Next, tell the agent the key is ready. It will read $FPR_FILE and wire the"
say "fingerprint into src/config/identity.ts, DISCLOSURE.md and SECURITY.md,"
say "where a test checks that the documents and the declaration agree."

finish
